package basicprograms;

import java.util.Scanner;



class Ex{
	public void user()throws Exception {
		
		user();
	}
}
public class HierachyExcepton {
	public static void main(String[] args) {
		try {
			
			int a[]=new int[Integer.MAX_VALUE];
		}
		catch(Throwable a)
		{
			System.out.println("inside main is handled");
		}
		
	}

}
